name: portfolio
description: Portfolio app especially for web
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.5
#  file_saver: ^0.1.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  lint:
  open_file: ^3.2.1
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
